export const audioTracks = [
  {
    id: 'abyss-forest',
    title: 'Dungeon Ambience',
    biome: 'Abyss Forest',
    section: 'home',
    src: '/audio/track-01.ogg',
    author: 'yd',
    license: 'CC0',
    sourceUrl: 'https://opengameart.org/content/dungeon-ambience',
    attributionRequired: false,
  },
  {
    id: 'blood-ruins',
    title: 'I swear I saw it',
    biome: 'Blood Ruins',
    section: 'projects',
    src: '/audio/track-02.ogg',
    author: 'yd',
    license: 'CC0',
    sourceUrl: 'https://opengameart.org/content/i-swear-i-saw-it-background-track',
    attributionRequired: false,
  },
  {
    id: 'obsidian-forge',
    title: 'EmptyCity',
    biome: 'Obsidian Forge',
    section: 'skills',
    src: '/audio/track-03.ogg',
    author: 'yd',
    license: 'CC0',
    sourceUrl: 'https://opengameart.org/content/emptycity-background-music',
    attributionRequired: false,
  },
  {
    id: 'arcane-library',
    title: 'Evil Temple Ambiance Loop',
    biome: 'Arcane Library',
    section: 'library',
    src: '/audio/track-04.ogg',
    author: 'Brandon Morris / HaelDB',
    license: 'CC0 or OGA-BY 3.0',
    sourceUrl: 'https://opengameart.org/content/evil-temple-ambiance-loop',
    attributionRequired: false,
  },
  {
    id: 'silent-graveyard',
    title: 'Ambient Relaxing Loop',
    biome: 'Silent Graveyard',
    section: 'contact',
    src: '/audio/track-05.ogg',
    author: 'isaiah658',
    license: 'CC0',
    sourceUrl: 'https://opengameart.org/content/ambient-relaxing-loop',
    attributionRequired: false,
  },
];

export default audioTracks;
