name = "cursed-biomes-portfolio"
main = "cloudflare/worker.mjs"
compatibility_date = "2025-06-01"

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "cursed-biomes-portfolio"
database_id = "9b05fa00-2c95-4b66-8e8f-e13ba4812b9f"
migrations_dir = "cloudflare/migrations"
