window.CursedBiomesContent = {
  defaultLocale: 'en',
  supportedLocales: ['en', 'vi'],
  translations: {
    en: {
      'meta.title': 'The Cursed Biomes Portfolio',
      'meta.description': 'The Cursed Biomes Portfolio by Pham Minh Sang, a dark fantasy Unity developer portfolio shell.',
      'loading.kicker': 'Moonlit gate',
      'loading.title': 'The Cursed Biomes Portfolio',
      'brand.aria': 'Back to home',
      'brand.name': 'The Cursed Biomes',
      'nav.aria': 'Primary navigation',
      'nav.projects': 'Projects',
      'nav.tryNow': 'Try Now',
      'nav.skills': 'Skills',
      'nav.library': 'Library',
      'nav.contact': 'Contact',
      'audio.aria': 'Ambient audio controls',
      'audio.prev.aria': 'Previous track',
      'audio.prev': 'Prev',
      'audio.next.aria': 'Next track',
      'audio.next': 'Next',
      'audio.volume.aria': 'Audio volume',
      'audio.enable': 'Enable Sound',
      'audio.mute': 'Mute Sound',
      'motion.reduce': 'Reduce Motion',
      'motion.enable': 'Motion On',
      'language.aria': 'Language selector',
      'language.en': 'EN',
      'language.vi': 'VI',
      'hero.eyebrow': 'Unity Developer / Gameplay Programmer',
      'hero.name': 'Pham Minh Sang',
      'hero.lede': 'A dark fantasy portfolio shaped like a game menu, built to showcase Unity systems, WebGL demos, live GitHub projects, and clean product thinking.',
      'hero.actions.aria': 'Hero actions',
      'hero.enterDemo': 'Enter Demo',
      'hero.viewProjects': 'View Projects',
      'hero.downloadCv': 'Download CV',
      'hero.stat.focus.label': 'Focus',
      'hero.stat.focus.value': 'Unity / C#',
      'hero.stat.mode.label': 'Mode',
      'hero.stat.mode.value': 'WebGL ready',
      'hero.stat.handle.label': 'Handle',
      'hero.stat.handle.value': 'PiupiuTenshi',
      'hero.avatar.alt': 'Pham Minh Sang dark fantasy portfolio avatar',
      'character.eyebrow': 'Character sheet',
      'character.title': 'Intern / Fresher Unity Developer',
      'character.build.title': 'Build style',
      'character.build.body': 'Gameplay-first, UI-conscious, and comfortable moving between Unity, C#, backend APIs, automation, and portfolio-grade presentation.',
      'character.quest.title': 'Current quest',
      'character.quest.body': 'Turn project work into a sharp recruiter experience with live repos, WebGL proof, contact flow, and admin visibility in later phases.',
      'character.contact.title': 'Contact routes',
      'character.contact.body': 'GitHub for code, Zalo for fast contact, CV for recruiter review, and chatbot for guided navigation.',
      'projects.eyebrow': 'Live GitHub relics',
      'projects.title': 'Dynamic project showcase',
      'projects.filters.aria': 'Project filters',
      'projects.filter.all': 'All',
      'projects.filter.featured': 'Featured',
      'projects.filter.web': 'Web',
      'projects.filter.security': 'Security',
      'projects.filter.management': 'Management',
      'repo.status.prepare': 'Preparing GitHub sync...',
      'repo.status.checking': 'Checking local relic cache...',
      'repo.status.cache': 'Loaded {count} repos from cache. Refreshing GitHub...',
      'repo.status.live': 'Live from GitHub. {count} visible repos.',
      'repo.status.fallback': 'Using fallback data. {message}',
      'repo.loading.type': 'Loading',
      'repo.loading.title': 'Summoning repositories',
      'repo.loading.body': 'GitHub project relics are being fetched. Fallback data will appear if the API is unavailable.',
      'repo.empty.type': 'Empty',
      'repo.empty.title': 'No relics found',
      'repo.empty.body': 'Try another filter or wait for GitHub to wake up.',
      'repo.defaultDescription': 'No README description yet. Open GitHub to inspect the relic.',
      'repo.meta.mixed': 'Mixed',
      'repo.meta.stars': '{count} stars',
      'repo.meta.forks': '{count} forks',
      'repo.meta.pushed': 'Pushed {date}',
      'repo.meta.unknown': 'Unknown',
      'repo.featuredCategory': 'Featured / {category}',
      'repo.action.viewCode': 'View Code',
      'repo.action.demo': 'Demo',
      'repo.action.tryNow': 'Try Now',
      'repo.action.preview': 'Preview',
      'repo.action.docs': 'Docs',
      'repo.fallback.techweb': 'Web platform project prepared for live GitHub sync and case-study routing.',
      'repo.fallback.pii': 'Privacy-preserving vertical fragmentation project for PII protection.',
      'repo.fallback.academic': 'Academic performance management system for tracking learning outcomes.',
      'demo.eyebrow': 'Unity WebGL Try Now',
      'demo.title': 'Try Now gate',
      'demo.image.alt': 'Dark fantasy UI UX complete reference',
      'demo.slot': 'Playable browser slot',
      'demo.overlay': 'Open the WebGL gate in a lazy-loaded modal',
      'demo.tryNow': 'Try Now',
      'demo.reset': 'Reset Gate',
      'demo.note': 'This Phase 3 slot uses a lightweight WebGL-style demo page. Replace `public/games/biome-gate` with a Unity WebGL build when it is ready.',
      'demo.progress.aria': 'Demo loading progress',
      'skills.eyebrow': 'Skill runes',
      'skills.title': 'Tools and systems',
      'skill.unity': 'Unity',
      'skill.csharp': 'C#',
      'skill.gameplay': 'Gameplay',
      'skill.webgl': 'WebGL',
      'skill.react': 'React',
      'skill.node': 'Node API',
      'skill.postgres': 'PostgreSQL',
      'skill.github': 'GitHub API',
      'skill.admin': 'Admin UX',
      'skill.automation': 'Automation',
      'library.eyebrow': 'Arcane library',
      'library.title': 'Quotes and books',
      'library.quote': '"Programs must be written for people to read, and only incidentally for machines to execute."',
      'library.quoteAuthor': 'Harold Abelson',
      'library.book.patterns.title': 'Game Programming Patterns',
      'library.book.patterns.body': 'Systems thinking for cleaner gameplay architecture.',
      'library.book.clean.title': 'Clean Code',
      'library.book.clean.body': 'Readable code habits for long-lived projects and teams.',
      'contact.eyebrow': 'Contact portal',
      'contact.title': 'Ready for recruiter review',
      'contact.github': 'GitHub',
      'contact.zalo': 'Zalo',
      'contact.cv': 'CV',
      'chat.aria': 'Mini chatbot',
      'chat.toggle': 'Chat',
      'chat.head.title': 'Gate guide',
      'chat.head.mode': 'Contact mode',
      'chat.intro': 'Choose a route or leave a message. I can save it for Sang.',
      'chat.quick.projects': 'Projects',
      'chat.quick.demo': 'Demo',
      'chat.quick.cv': 'CV',
      'chat.quick.zalo': 'Zalo',
      'chat.quickMessage.projects': 'Show Unity projects',
      'chat.quickMessage.demo': 'Open WebGL demo',
      'chat.quickMessage.cv': 'Download CV',
      'chat.quickMessage.zalo': 'Contact via Zalo',
      'chat.reply.projects': 'Project relics now sync from GitHub with local cache and fallback data.',
      'chat.reply.demo': 'Use the Try Now gate to open the lazy-loaded WebGL modal. Full Unity export can replace the placeholder folder later.',
      'chat.reply.cv': 'The CV route is wired, but the final PDF is still marked pending in the Phase 0 status doc.',
      'chat.reply.zalo': 'Use the Zalo portal in Contact for the fastest reply path.',
      'chat.reply.fallback': 'That route is reserved for a later phase.',
      'chat.form.message': 'Message',
      'chat.form.messagePlaceholder': 'Tell Sang what you want to discuss...',
      'chat.form.contact': 'Email or Zalo optional',
      'chat.form.contactPlaceholder': 'email@example.com or 089...',
      'chat.form.submit': 'Send Message',
      'chat.status.saving': 'Saving message...',
      'chat.status.saved': 'Saved to inbox as {messageId}',
      'chat.status.unavailable': 'Run the local server to enable saving.',
      'chat.reply.saved': 'Saved. Sang can review this from the admin inbox.',
      'chat.reply.inboxError': 'I could not reach the local inbox yet: {message}',
      'chat.action.openAdmin': 'Open Admin Gate',
      'webgl.eyebrow': 'Try Now',
      'webgl.title': 'Biome Gate Demo',
      'webgl.close.aria': 'Close WebGL demo',
      'webgl.close': 'Close',
      'webgl.warning': 'Mobile devices may load WebGL slowly. Use fullscreen on desktop for the best run.',
      'webgl.loader.opening': 'Opening the cursed gate...',
      'webgl.loader.biomes': 'Awakening forgotten biomes...',
      'webgl.loader.binding': 'Binding WebGL spirits...',
      'webgl.loader.loop': 'Summoning gameplay loop...',
      'webgl.loader.enter': 'Enter the demo.',
      'webgl.frame.title': 'Biome Gate WebGL demo',
      'webgl.fullscreen': 'Fullscreen',
      'webgl.openSeparate': 'Open Separate',
      'webgl.fallback': 'Fallback GitHub',
      'audio.track.0.title': 'Abyss Forest',
      'audio.track.0.section': 'Home',
      'audio.track.1.title': 'Blood Ruins',
      'audio.track.1.section': 'Projects',
      'audio.track.2.title': 'Obsidian Forge',
      'audio.track.2.section': 'Skills',
      'audio.track.3.title': 'Arcane Library',
      'audio.track.3.section': 'Library',
      'audio.track.4.title': 'Silent Graveyard',
      'audio.track.4.section': 'Contact',
    },
    vi: {
      'meta.title': 'The Cursed Biomes Portfolio',
      'meta.description': 'The Cursed Biomes Portfolio của Phạm Minh Sáng, portfolio Unity developer phong cách dark fantasy.',
      'loading.kicker': 'Cổng trăng',
      'loading.title': 'The Cursed Biomes Portfolio',
      'brand.aria': 'Quay về trang đầu',
      'brand.name': 'The Cursed Biomes',
      'nav.aria': 'Điều hướng chính',
      'nav.projects': 'Dự án',
      'nav.tryNow': 'Chơi thử',
      'nav.skills': 'Kỹ năng',
      'nav.library': 'Thư viện',
      'nav.contact': 'Liên hệ',
      'audio.aria': 'Điều khiển âm thanh nền',
      'audio.prev.aria': 'Track trước',
      'audio.prev': 'Trước',
      'audio.next.aria': 'Track tiếp theo',
      'audio.next': 'Tiếp',
      'audio.volume.aria': 'Âm lượng',
      'audio.enable': 'Bật âm thanh',
      'audio.mute': 'Tắt âm',
      'motion.reduce': 'Giảm chuyển động',
      'motion.enable': 'Bật chuyển động',
      'language.aria': 'Chọn ngôn ngữ',
      'language.en': 'EN',
      'language.vi': 'VI',
      'hero.eyebrow': 'Unity Developer / Gameplay Programmer',
      'hero.name': 'Phạm Minh Sáng',
      'hero.lede': 'Portfolio dark fantasy như một game menu, dùng để showcase hệ thống Unity, WebGL demo, GitHub project live và tư duy sản phẩm gọn gàng.',
      'hero.actions.aria': 'Hành động chính',
      'hero.enterDemo': 'Vào demo',
      'hero.viewProjects': 'Xem dự án',
      'hero.downloadCv': 'Tải CV',
      'hero.stat.focus.label': 'Trọng tâm',
      'hero.stat.focus.value': 'Unity / C#',
      'hero.stat.mode.label': 'Chế độ',
      'hero.stat.mode.value': 'Sẵn sàng WebGL',
      'hero.stat.handle.label': 'Handle',
      'hero.stat.handle.value': 'PiupiuTenshi',
      'hero.avatar.alt': 'Avatar portfolio dark fantasy của Phạm Minh Sáng',
      'character.eyebrow': 'Hồ sơ nhân vật',
      'character.title': 'Intern / Fresher Unity Developer',
      'character.build.title': 'Phong cách build',
      'character.build.body': 'Ưu tiên gameplay, chú ý UI, và có thể chuyển đổi giữa Unity, C#, backend API, automation và phần trình bày portfolio.',
      'character.quest.title': 'Nhiệm vụ hiện tại',
      'character.quest.body': 'Biến project thành trải nghiệm rõ ràng cho recruiter với repo live, bằng chứng WebGL, luồng liên hệ và admin visibility ở các phase sau.',
      'character.contact.title': 'Kênh liên hệ',
      'character.contact.body': 'GitHub để xem code, Zalo để liên hệ nhanh, CV để recruiter review, và chatbot để dẫn hướng.',
      'projects.eyebrow': 'Relic GitHub live',
      'projects.title': 'Showcase dự án động',
      'projects.filters.aria': 'Bộ lọc dự án',
      'projects.filter.all': 'Tất cả',
      'projects.filter.featured': 'Nổi bật',
      'projects.filter.web': 'Web',
      'projects.filter.security': 'Security',
      'projects.filter.management': 'Quản lý',
      'repo.status.prepare': 'Đang chuẩn bị đồng bộ GitHub...',
      'repo.status.checking': 'Đang kiểm tra cache relic local...',
      'repo.status.cache': 'Đã tải {count} repo từ cache. Đang refresh GitHub...',
      'repo.status.live': 'Đang dùng dữ liệu GitHub live. Có {count} repo hiển thị.',
      'repo.status.fallback': 'Đang dùng dữ liệu fallback. {message}',
      'repo.loading.type': 'Đang tải',
      'repo.loading.title': 'Đang triệu hồi repository',
      'repo.loading.body': 'Các relic project từ GitHub đang được fetch. Nếu API không khả dụng, dữ liệu fallback sẽ hiện ra.',
      'repo.empty.type': 'Trống',
      'repo.empty.title': 'Không tìm thấy relic',
      'repo.empty.body': 'Thử bộ lọc khác hoặc chờ GitHub thức dậy.',
      'repo.defaultDescription': 'Chưa có mô tả README. Mở GitHub để xem relic.',
      'repo.meta.mixed': 'Hỗn hợp',
      'repo.meta.stars': '{count} sao',
      'repo.meta.forks': '{count} fork',
      'repo.meta.pushed': 'Cập nhật {date}',
      'repo.meta.unknown': 'Không rõ',
      'repo.featuredCategory': 'Nổi bật / {category}',
      'repo.action.viewCode': 'Xem code',
      'repo.action.demo': 'Demo',
      'repo.action.tryNow': 'Chơi thử',
      'repo.action.preview': 'Preview',
      'repo.action.docs': 'Docs',
      'repo.fallback.techweb': 'Project web platform đã chuẩn bị cho GitHub sync live và case-study routing.',
      'repo.fallback.pii': 'Project vertical fragmentation bảo vệ quyền riêng tư cho dữ liệu PII.',
      'repo.fallback.academic': 'Hệ thống quản lý kết quả học tập để theo dõi learning outcomes.',
      'demo.eyebrow': 'Unity WebGL Chơi thử',
      'demo.title': 'Cổng chơi thử',
      'demo.image.alt': 'Ảnh tham chiếu UI UX dark fantasy hoàn thiện',
      'demo.slot': 'Slot chơi trên trình duyệt',
      'demo.overlay': 'Mở cổng WebGL bằng modal lazy-load',
      'demo.tryNow': 'Chơi thử',
      'demo.reset': 'Reset cổng',
      'demo.note': 'Slot Phase 3 này đang dùng trang demo nhẹ kiểu WebGL. Khi build Unity WebGL sẵn sàng, thay thư mục `public/games/biome-gate` là được.',
      'demo.progress.aria': 'Tiến trình tải demo',
      'skills.eyebrow': 'Rune kỹ năng',
      'skills.title': 'Công cụ và hệ thống',
      'skill.unity': 'Unity',
      'skill.csharp': 'C#',
      'skill.gameplay': 'Gameplay',
      'skill.webgl': 'WebGL',
      'skill.react': 'React',
      'skill.node': 'Node API',
      'skill.postgres': 'PostgreSQL',
      'skill.github': 'GitHub API',
      'skill.admin': 'Admin UX',
      'skill.automation': 'Automation',
      'library.eyebrow': 'Thư viện arcane',
      'library.title': 'Quote và sách',
      'library.quote': '"Programs must be written for people to read, and only incidentally for machines to execute."',
      'library.quoteAuthor': 'Harold Abelson',
      'library.book.patterns.title': 'Game Programming Patterns',
      'library.book.patterns.body': 'Tư duy hệ thống để thiết kế gameplay architecture sạch hơn.',
      'library.book.clean.title': 'Clean Code',
      'library.book.clean.body': 'Thói quen viết code dễ đọc cho project và team dài hạn.',
      'contact.eyebrow': 'Cổng liên hệ',
      'contact.title': 'Sẵn sàng cho recruiter review',
      'contact.github': 'GitHub',
      'contact.zalo': 'Zalo',
      'contact.cv': 'CV',
      'chat.aria': 'Mini chatbot',
      'chat.toggle': 'Chat',
      'chat.head.title': 'Gate guide',
      'chat.head.mode': 'Chế độ liên hệ',
      'chat.intro': 'Chọn một hướng đi hoặc để lại tin nhắn. Mình có thể lưu lại cho Sang.',
      'chat.quick.projects': 'Dự án',
      'chat.quick.demo': 'Demo',
      'chat.quick.cv': 'CV',
      'chat.quick.zalo': 'Zalo',
      'chat.quickMessage.projects': 'Show Unity projects',
      'chat.quickMessage.demo': 'Open WebGL demo',
      'chat.quickMessage.cv': 'Download CV',
      'chat.quickMessage.zalo': 'Contact via Zalo',
      'chat.reply.projects': 'Các project relic hiện đã sync từ GitHub, có cache local và fallback data.',
      'chat.reply.demo': 'Dùng cổng Chơi thử để mở WebGL modal lazy-load. Sau này có thể thay folder placeholder bằng Unity export thật.',
      'chat.reply.cv': 'Route CV đã được nối, nhưng file PDF cuối vẫn đang được đánh dấu pending trong Phase 0 status doc.',
      'chat.reply.zalo': 'Dùng cổng Zalo trong phần Liên hệ để phản hồi nhanh nhất.',
      'chat.reply.fallback': 'Hướng này được để dành cho phase sau.',
      'chat.form.message': 'Tin nhắn',
      'chat.form.messagePlaceholder': 'Nói cho Sang biết bạn muốn trao đổi gì...',
      'chat.form.contact': 'Email hoặc Zalo tùy chọn',
      'chat.form.contactPlaceholder': 'email@example.com hoặc 089...',
      'chat.form.submit': 'Gửi tin nhắn',
      'chat.status.saving': 'Đang lưu tin nhắn...',
      'chat.status.saved': 'Đã lưu vào inbox với mã {messageId}',
      'chat.status.unavailable': 'Chạy local server để bật lưu tin nhắn.',
      'chat.reply.saved': 'Đã lưu. Sang có thể xem lại trong admin inbox.',
      'chat.reply.inboxError': 'Mình chưa kết nối được local inbox: {message}',
      'chat.action.openAdmin': 'Mở Admin Gate',
      'webgl.eyebrow': 'Chơi thử',
      'webgl.title': 'Biome Gate Demo',
      'webgl.close.aria': 'Đóng WebGL demo',
      'webgl.close': 'Đóng',
      'webgl.warning': 'Thiết bị mobile có thể tải WebGL chậm. Desktop fullscreen sẽ chạy tốt hơn.',
      'webgl.loader.opening': 'Đang mở cổng nguyền...',
      'webgl.loader.biomes': 'Đánh thức các biome bị lãng quên...',
      'webgl.loader.binding': 'Ràng buộc WebGL spirits...',
      'webgl.loader.loop': 'Triệu hồi gameplay loop...',
      'webgl.loader.enter': 'Vào demo.',
      'webgl.frame.title': 'Biome Gate WebGL demo',
      'webgl.fullscreen': 'Toàn màn hình',
      'webgl.openSeparate': 'Mở riêng',
      'webgl.fallback': 'GitHub fallback',
      'audio.track.0.title': 'Rừng Vực Sâu',
      'audio.track.0.section': 'Trang đầu',
      'audio.track.1.title': 'Tàn Tích Máu',
      'audio.track.1.section': 'Dự án',
      'audio.track.2.title': 'Lò Rèn Obsidian',
      'audio.track.2.section': 'Kỹ năng',
      'audio.track.3.title': 'Thư Viện Arcane',
      'audio.track.3.section': 'Thư viện',
      'audio.track.4.title': 'Nghĩa Địa Tĩnh Lặng',
      'audio.track.4.section': 'Liên hệ',
    },
  },
  audioTracks: [
    { titleKey: 'audio.track.0.title', sectionKey: 'audio.track.0.section', src: 'public/audio/track-01.ogg' },
    { titleKey: 'audio.track.1.title', sectionKey: 'audio.track.1.section', src: 'public/audio/track-02.ogg' },
    { titleKey: 'audio.track.2.title', sectionKey: 'audio.track.2.section', src: 'public/audio/track-03.ogg' },
    { titleKey: 'audio.track.3.title', sectionKey: 'audio.track.3.section', src: 'public/audio/track-04.ogg' },
    { titleKey: 'audio.track.4.title', sectionKey: 'audio.track.4.section', src: 'public/audio/track-05.ogg' },
  ],
  webglLoadLineKeys: [
    'webgl.loader.opening',
    'webgl.loader.biomes',
    'webgl.loader.binding',
    'webgl.loader.loop',
    'webgl.loader.enter',
  ],
  webglDemo: {
    slug: 'biome-gate',
    titleKey: 'webgl.title',
    repoName: 'Unity2DTopDown',
    webglEnabled: true,
    tryNowUrl: 'public/games/biome-gate/index.html',
    fallbackUrl: 'https://github.com/PiupiuTenshi',
    isPlaceholder: true,
  },
  repoSettings: [
    {
      owner: 'PiupiuTenshi',
      repoName: 'TechWeb-2026',
      visible: true,
      featured: true,
      priority: 1,
      category: 'web',
      tryNowUrl: null,
      caseStudyUrl: '/projects/techweb-2026',
    },
    {
      owner: 'PiupiuTenshi',
      repoName: 'Privacy-Preserving-Vertical-Fragmentation-PII-Shield',
      visible: true,
      featured: true,
      priority: 2,
      category: 'security',
      tryNowUrl: null,
      caseStudyUrl: '/projects/pii-shield',
      customTitle: 'PII Shield',
    },
    {
      owner: 'PiupiuTenshi',
      repoName: 'Academic-performance-management',
      visible: true,
      featured: true,
      priority: 3,
      category: 'management',
      tryNowUrl: null,
      caseStudyUrl: '/projects/academic-performance-management',
      customTitle: 'Academic Performance',
    },
  ],
  fallbackRepos: [
    {
      id: 1,
      name: 'TechWeb-2026',
      full_name: 'PiupiuTenshi/TechWeb-2026',
      descriptionKey: 'repo.fallback.techweb',
      html_url: 'https://github.com/PiupiuTenshi/TechWeb-2026',
      homepage: null,
      language: 'JavaScript',
      stargazers_count: 0,
      forks_count: 0,
      open_issues_count: 0,
      pushed_at: '2026-06-10T00:00:00Z',
      updated_at: '2026-06-10T00:00:00Z',
      archived: false,
      fork: false,
      topics: ['web', 'portfolio'],
    },
    {
      id: 2,
      name: 'Privacy-Preserving-Vertical-Fragmentation-PII-Shield',
      full_name: 'PiupiuTenshi/Privacy-Preserving-Vertical-Fragmentation-PII-Shield',
      descriptionKey: 'repo.fallback.pii',
      html_url: 'https://github.com/PiupiuTenshi/Privacy-Preserving-Vertical-Fragmentation-PII-Shield',
      homepage: null,
      language: 'Python',
      stargazers_count: 0,
      forks_count: 0,
      open_issues_count: 0,
      pushed_at: '2026-06-10T00:00:00Z',
      updated_at: '2026-06-10T00:00:00Z',
      archived: false,
      fork: false,
      topics: ['privacy', 'security', 'database'],
    },
    {
      id: 3,
      name: 'Academic-performance-management',
      full_name: 'PiupiuTenshi/Academic-performance-management',
      descriptionKey: 'repo.fallback.academic',
      html_url: 'https://github.com/PiupiuTenshi/Academic-performance-management',
      homepage: null,
      language: 'C#',
      stargazers_count: 0,
      forks_count: 0,
      open_issues_count: 0,
      pushed_at: '2026-06-10T00:00:00Z',
      updated_at: '2026-06-10T00:00:00Z',
      archived: false,
      fork: false,
      topics: ['management', 'academic'],
    },
  ],
};
